### ISSUE TITLE
Bambuser SPM failing to download due to 403

### ISSUE THREAD

**Issue by joshgare** [bambuser/BambuserPlayerSDK-iOS#12]
We're importing Bambuser via SPM and we're unable to do so.

We're getting the following error.

```
error: failed downloading 'https://cdn.liveshopping.bambuser.com/public/download/BambuserPlayerSDK-1.5.0-release.xcframework.zip' which is required by binary target 'BambuserPlayerSDK': badResponseStatusCode(403)
```

Even if you go to https://cdn.liveshopping.bambuser.com/public/download/BambuserPlayerSDK-1.5.0-release.xcframework.zip via the browser you can get the access denied message. Also the same for the previous version of the SDK.

**Comment by saeidbasirnia** [comment]
The issue should be resolved now, please make sure to clean `DerivedData` and `SPM cache` first.

**Comment by saeidbasirnia** [comment]
I'll close this issue but feel free to reopen this or create a new one if you had any problems or questions.
