### ISSUE TITLE
Cocospods support for React Native

### ISSUE THREAD

**Issue by emailvenkatm** [bambuser/BambuserPlayerSDK-iOS#13]
Hello,

Wondering if there is any way that we can integrate this SDK in our react-native project as I see in the documentation that this SDK doesn't support cocoapods.

**Comment by saeidbasirnia** [comment]
Hi, 
Currently SDK is accessible through SPM and it's not available with Cocoapods, but we're looking into this. 
Unfortunately, I don't have an ETA but I'll update the thread with updates.

**Comment by CTOverton** [comment]
@saeidbasirnia I just opened a pr to hopefully make your lives a little easier. Let me know if there is anything else you need but this should do it.

- #14

**Comment by saeidbasirnia** [comment]
Hi @CTOverton, 
`BambuserPlayerSDK` is now available through [Cocoapods](https://github.com/bambuser/BambuserPlayerSDK-iOS#cocoapods). 
Please let us know if you're facing any issues or have any questions.

**Comment by CTOverton** [comment]
Thank you @saeidbasirnia !
