### ISSUE TITLE
Upgrade to Firebase 11

### ISSUE THREAD

**Issue by joshuapoq** [bambuser/BambuserPlayerSDK-iOS#17]
Please can you look to support Firebase 11; or potentially plan to remove the Firebase dependency to avoid version conflicts?

**Comment by saeidbasirnia** [comment]
Hi, 
Yes we'll look into that soon but removing Firebase dependency is not in our roadmap.

**Comment by saeidbasirnia** [comment]
Hi @joshuapoq, just an update on this, from next release of `BambuserPlayerSDK` we will support Firebase SDK v11.

**Comment by saeidbasirnia** [comment]
@joshuapoq 
An update about this issue, from [2.0.0](https://github.com/bambuser/BambuserPlayerSDK-iOS/tree/2.0.0) release, now SDK supports Firebase SDK `11.0.0+`.

**Comment by joshuapoq** [comment]
Thanks Saeid! ❤️
