### ISSUE TITLE
Issue with SPM Integration of BumbuseSDK: Error in Console

### ISSUE THREAD

**Issue by simonpeter-97** [bambuser/BambuserPlayerSDK-iOS#20]
We found an issue while using SPM for the SDK. It shows the following error in the console when we import BumbuseSDK in classes:
Xcode: 15.2
Swift version: 5

![Screenshot 2024-09-30 at 12 15 50 PM](https://github.com/user-attachments/assets/6aebc156-1b3d-46f9-92a7-1ffdeafb1969)

Are we missing something in our setup?

A fast response would be appreciated.

**Comment by saeidbasirnia** [comment]
Hi @simonpeter-97, 
Which version of `BambuserPlayerSDK` are you using? please make sure you're using latest version [1.5.4](https://github.com/bambuser/BambuserPlayerSDK-iOS/tree/1.5.4).
Do you have Firebase SDK dependency in your project? if so, which version?

Also try to wipe SPM cache and derived data
```
/Library/Caches/org.swift.swiftpm
/Library/org.swift.swiftpm
/Library/Developer/Xcode/DerivedData
```

**Comment by simonpeter-97** [comment]
@saeidbasirnia san, We are using version 1.5.4. Yes, we do have a Firebase dependency, but we also tried creating a new project without Firebase and faced the same problem. Additionally, we tested a demo app, and the same error appeared. We tried it on different machines but encountered the same issue. 
![Screenshot 2024-09-30 at 1 12 22 PM](https://github.com/user-attachments/assets/836f6777-1b83-4cc2-a99a-de7ddc977dda)

**Comment by saeidbasirnia** [comment]
It maybe related to Xcode version you're using and its toolchain 🤔
Did the other machine also using Xcode 15.2?
Is it possible for you to update Xcode versions? No issues on Xcode 15.4 and 15.3 on my side. I don't have Xcode 15.2 right now to test.

**Comment by simonpeter-97** [comment]
@saeidbasirnia Thanks, In the latest Xcode version, it's working. Thanks for the help! It seems the SDK requires Xcode 15.3 or above
