### ISSUE TITLE
Firebase fails to build on Xcode 16

### ISSUE THREAD

**Issue by CTOverton** [bambuser/BambuserPlayerSDK-iOS#22]
Xcode 16 caused a new build issue for React Native. The underlying issue is with the native Firebase sdks. More details can be found here
https://github.com/invertase/react-native-firebase/issues/8020

This issue was resolved in the native Firebase sdks, they just need to be updated in the podspec: https://github.com/bambuser/BambuserPlayerSDK-iOS/pull/21

**Comment by saeidbasirnia** [comment]
PlayerSDK currently requires Firebase 10.x.x. we're working on a new release this week to bump the Firebase SDK version to 11.x

**Comment by saeidbasirnia** [comment]
From [2.0.0](https://github.com/bambuser/BambuserPlayerSDK-iOS/tree/2.0.0) release, now SDK supports Firebase SDK 11.0.0+.
