### ISSUE TITLE
Conflict Between our project's Firebase dependency and sub-dependency in BambuserPlayerSDK-iOS

### ISSUE THREAD

**Issue by DanielDM2020** [bambuser/BambuserPlayerSDK-iOS#3]
### Issue Summary
We are experiencing a dependency conflict in our project which utilizes Firebase as a direct dependency. The package from BambuserPlayerSDK that we have integrated into our project also includes Firebase as a sub-dependency but with a different version, leading to a collision between the two Firebase versions. 

Since we are currently using MLKit to capture barcodes in our project, we need version 8.6 of Firebase, which is not compatible with newer versions.

### Expected Behavior
The project should be able to maintain a consistent Firebase version (in this case, version 8 required by MLKit) without encountering conflicts arising from the sub-dependency version included in the BambuserPlayerSDK-iOS package.

**Comment by saeidbasirnia** [comment]
Hi Daniel, 
Thanks for reaching out and letting us know about this issue.
We're currently investigating solutions to resolve the issue, meanwhile can you provide more details about the library causing this conflict? 

Thank you.

**Comment by DanielDM2020** [comment]
We use firebase as a dependency in our project, especially Remote Config and MLKit. For this we need version 8.6 of Firebase, but this conflicts with the version used in the BambuserSDK.

**Comment by saeidbasirnia** [comment]
@DanielDM2020 this issue should be resolved with [release 1.4.0](https://github.com/bambuser/BambuserPlayerSDK-iOS/tree/1.4.0). 
Please make sure cache is cleaned and update package to latest version.
