### ISSUE TITLE
Close button not firing close event

### ISSUE THREAD

**Issue by joshgare** [bambuser/BambuserPlayerSDK-iOS#5]
When pressing the close button on the top right of the player view the SDK does not fire the `BambuserPlayerEvent.closed`. This means it is not possible to dismiss the view controller. This is using 1.3.0 SDK.

![Simulator Screenshot - iPhone 15 Pro Max - 2024-02-13 at 11 45 33](https://github.com/bambuser/BambuserPlayerSDK-iOS/assets/113687/26137996-e6fe-4007-a486-70a24246760c)

**Comment by saeidbasirnia** [comment]
Hi @joshgare, 
When `PlayerConfiguration.pipConfig.isEnabled == true`, there won't be a close button as the screenshot above. This button will minimize the view and start the PIP. (Please note that PIP is not working in iPhone simulator at this point, you either need to test it on iPad or a real device).
In this case, closing this view, should be handled by the developer.
if `PlayerConfiguration.pipConfig.isEnabled == false`, then there will be a **`X`**, at the top right corner.
