### ISSUE TITLE
Video view displaying whitespace in safe area

### ISSUE THREAD

**Issue by joshgare** [bambuser/BambuserPlayerSDK-iOS#6]
In v1.3.0 you can see the video does not extend below the safe area. This is causing a white bar to appear at the bottom of the player.

![Simulator Screenshot - iPhone 15 Pro Max - 2024-02-13 at 11 45 33](https://github.com/bambuser/BambuserPlayerSDK-iOS/assets/113687/b3664bbd-4c75-4185-911c-7d7eab9b69bd)

**Comment by saeidbasirnia** [comment]
Issue is resolved in [release 1.4.0](https://github.com/bambuser/BambuserPlayerSDK-iOS/tree/1.4.0)
