### ISSUE TITLE
Upgrading from v1.2.2 to v1.3.0 missing architecture

### ISSUE THREAD

**Issue by joshgare** [bambuser/BambuserPlayerSDK-iOS#7]
We've upgraded the Bambuser iOS SDK from v1.2.2 to 1.3.0 but this is now preventing our project from compiling.

```
▸ Linking VennUAT
⚠️  ld: Could not find or use auto-linked library 'swiftObservation'
⚠️  ld: Could not find or use auto-linked library 'swiftCompatibilityPacks'
⚠️  ld: Could not find or use auto-linked framework 'Symbols'
⚠️  ld: Could not find or use auto-linked framework 'BambuserPlayer'
⚠️  ld: Could not find or use auto-linked framework 'CoreAudioTypes'

❌  ld: symbol(s) not found for architecture arm64



❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Please note we have not made any other changes to our project other than upgrading the Bambuser SDK.

**Comment by saeidbasirnia** [comment]
Hi @joshgare, 
We'll look into this issue and will get back to you as soon as possible. 
Did you try to remove the caches and try again? 
We're also working on a new version of the SDK along with some improvements and fixes and we're planning to release it soon.

**Comment by joshgare** [comment]
@saeidbasirnia the issue still arises when you remove the cache and build from a clean build.

**Comment by saeidbasirnia** [comment]
New [release 1.4.0](https://github.com/bambuser/BambuserPlayerSDK-iOS/tree/1.4.0) is available now. 
Please make sure you cache is cleared and proceed with updating to latest version of the package. 
You can read what's new in this release [here](https://github.com/bambuser/BambuserPlayerSDK-iOS/blob/main/RELEASE_NOTES.md).

Please open a new issue if you faced any issues.

**Comment by joshgare** [comment]
This issue still stands in v1.4.0.

**Comment by saeidbasirnia** [comment]
@joshgare Can you provide more information about your project dependencies and what version of Xcode you're using?

Also few things to check:
- Does the project compiles without BambuserPlayerSDK dependency?
- If you added `-ObjC` flag to `Other Linker Flags` under Build settings, try removing it 
- The error showing `architecture arm64`, does the project build on simulator devices?

**Comment by joshgare** [comment]
- Project compiles correctly without the Bambuser dependency
- Our project requires the -ObjC linker flag due to other dependencies - this flag was set pre v1.3.0 and the SDK compiled without any issues
- Project runs and builds on simulator devices

**Comment by saeidbasirnia** [comment]
Thanks @joshgare for your reply.
I'm investigating this issue and will update the thread with more info soon.

**Comment by saeidbasirnia** [comment]
Hi @joshgare,
We updated the binary and removed the statically linked firebase dependencies, Now it's using firebase dynamically. 
Please use release [1.4.1](https://github.com/bambuser/BambuserPlayerSDK-iOS/tree/1.4.1). You can find more details [here](https://github.com/bambuser/BambuserPlayerSDK-iOS/tree/1.4.1)
Note that you should clear project and SPM caches first.
Let me know if you have any questions or issues 🙂

**Comment by saeidbasirnia** [comment]
Hi @joshgare, 
Any updates on this issue?

**Comment by joshgare** [comment]
Hi @saeidbasirnia - I
Will get this reviewed on our end ASAP this week.

**Comment by joshgare** [comment]
@saeidbasirnia this seems to have resolved itself on the latest version of Xcode!
