### ISSUE TITLE
Bambuser (1.4.0) and Firebase Duplicate Symbols

### ISSUE THREAD

**Issue by joshuapoq** [bambuser/BambuserPlayerSDK-iOS#8]
### Description
After the changes to remove Firebase at package level I believe you are still linking it statically under the hood. So when using the `-ObjC` linker flag and depending on both Firebase and Bambuser I'm unable to compile the app due to 1000s of duplicate symbols.

### Versions
- Xcode 15.3
- Bambuser 1.4.0

### Steps
- Create a new project and add bambuser and firebase as dependencies (with the latest versions).
- Add the `-ObjC` linker flag as [described here](https://github.com/firebase/firebase-ios-sdk/blob/main/SwiftPackageManager.md#requirements).

**Comment by saeidbasirnia** [comment]
Hi @joshuapoq, 

Thanks for reporting this issue, we are looking into this.

Meanwhile if you need to use Firebase SDK, you don't need to add `-ObjC` flag to your project settings and you can skip this step as described in Firebase documentation.
Simply add `Firebase` package to your project and your required products along with `BambuserPlayerSDK`.
You should be able to build your project and start using them.
Don't forget to clean your project and reset cache once you remove the flag.

Please let us know if you still facing issues.

**Comment by joshuapoq** [comment]
Just to note that `-ObjC` is not necessarily not required. I think Firebase are using ObjC to add a dynamic entry point using Objective-C that is also triggered if you access `Analytics.analytics()` so the above advise can be dangerous in rare case.

**Comment by saeidbasirnia** [comment]
Thanks @joshuapoq for your reply. 
 I'm investigating this issue and will update the thread with more info soon.

**Comment by saeidbasirnia** [comment]
Hi @joshuapoq, 
We updated the binary and removed the statically linked firebase dependencies, Now it's using firebase dynamically. 
Please use release [1.4.1](https://github.com/bambuser/BambuserPlayerSDK-iOS/tree/1.4.1). You can find more details [here](https://github.com/bambuser/BambuserPlayerSDK-iOS/tree/1.4.1)
Note that you should clear project and SPM caches first.
Let me know if you have any questions or issues 🙂

**Comment by joshuapoq** [comment]
Apologies, have been slow to return to this. After purging source packages all is working now! Thanks for the fast turnaround.
